# Generated by Django 3.2.6 on 2021-08-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedgerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(default='', max_length=30)),
                ('account_type', models.CharField(default='', max_length=2)),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
